### ISSUE TITLE
Error while entering a move.

### ISSUE THREAD

**Issue by GabrieleBattaglia** [tage64/chess-cli#23]
Hi Tage.
I was simply entering moves and I've got this tracebakc.
6... Nc6: nbd2                                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                               
  File "E:\Software\Chess-CLI\chess-cli.py", line 15, in <module>                                                                                                                                                
  File "E:\Software\Chess-CLI\chess_cli\main.py", line 63, in main                                                                                                                                               
  File "E:\Software\Chess-CLI\asyncio\runners.py", line 194, in run                                                                                                                                              
  File "E:\Software\Chess-CLI\asyncio\runners.py", line 118, in run                                                                                                                                              
  File "E:\Software\Chess-CLI\asyncio\base_events.py", line 687, in run_until_complete                                                                                                                           
  File "E:\Software\Chess-CLI\chess_cli\engine.py", line 84, in cmd_loop                                                                                                                                         
  File "E:\Software\Chess-CLI\chess_cli\record.py", line 535, in cmd_loop                                                                                                                                        
  File "E:\Software\Chess-CLI\chess_cli\repl.py", line 334, in cmd_loop                                                                                                                                          
  File "E:\Software\Chess-CLI\chess_cli\record.py", line 495, in prompt                                                                                                                                          
  File "E:\Software\Chess-CLI\chess_cli\repl.py", line 275, in prompt                                                                                                                                            
  File "E:\Software\Chess-CLI\chess_cli\fast_move_input.py", line 34, in exec_cmd                                                                                                                                
AssertionError

**Comment by GabrieleBattaglia** [comment]
I had another one here:
start: d4                                                                                                                                                                                                        
1. d4: nf6                                                                                                                                                                                                       
1... Nf6: c4                                                                                                                                                                                                     
2. c4: g6                                                                                                                                                                                                        
2... g6: nc3                                                                                                                                                                                                     
3. Nc3: bg7                                                                                                                                                                                                      
3... Bg7: e4                                                                                                                                                                                                     
4. e4: d6                                                                                                                                                                                                        
4... d6: f3                                                                                                                                                                                                      
5. f3: o-o                                                                                                                                                                                                       
5... O-O: be3                                                                                                                                                                                                    
6. Be3: nbd7                                                                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                                               
  File "E:\Software\Chess-CLI\chess-cli.py", line 15, in <module>                                                                                                                                                
  File "E:\Software\Chess-CLI\chess_cli\main.py", line 63, in main                                                                                                                                               
  File "E:\Software\Chess-CLI\asyncio\runners.py", line 194, in run                                                                                                                                              
  File "E:\Software\Chess-CLI\asyncio\runners.py", line 118, in run                                                                                                                                              
  File "E:\Software\Chess-CLI\asyncio\base_events.py", line 687, in run_until_complete                                                                                                                           
  File "E:\Software\Chess-CLI\chess_cli\engine.py", line 84, in cmd_loop                                                                                                                                         
  File "E:\Software\Chess-CLI\chess_cli\record.py", line 535, in cmd_loop                                                                                                                                        
  File "E:\Software\Chess-CLI\chess_cli\repl.py", line 334, in cmd_loop                                                                                                                                          
  File "E:\Software\Chess-CLI\chess_cli\record.py", line 495, in prompt                                                                                                                                          
  File "E:\Software\Chess-CLI\chess_cli\repl.py", line 275, in prompt                                                                                                                                            
  File "E:\Software\Chess-CLI\chess_cli\fast_move_input.py", line 34, in exec_cmd                                                                                                                                
AssertionError

**Comment by tage64** [comment]
Solved by ac20315d.
