### ISSUE TITLE
Adding an arrow

### ISSUE THREAD

**Issue by GabrieleBattaglia** [tage64/chess-cli#9]
I have the following traceback
start: ar add a3 c5                                                                                                                                                                                              
Traceback (most recent call last):                                                                                                                                                                               
  File "C:\Users\Utente\AppData\Local\Temp\ONEFIL~1\chess_cli\repl.py", line 53, in call_wrap_exception                                                                                                          
  File "C:\Users\Utente\AppData\Local\Temp\ONEFIL~1\chess_cli\repl.py", line 375, in cmd_func                                                                                                                    
  File "C:\Users\Utente\AppData\Local\Temp\ONEFIL~1\chess_cli\curr_move_cmds.py", line 332, in do_arrow                                                                                                          
AttributeError: 'Namespace' object has no attribute 'subcmd'. Did you mean: 'subcmds'?

**Comment by tage64** [comment]
Fixed by commit 16289dc8f.
